SendAndRecieveSMS/Models/FullSmsDetailModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Twilio.Rest.Api.V2010.Account;
using Twilio.Types;

namespace SendAndRecieveSMS.Models
{
    public class FullSmsDetailModel
    {
        public string sid { get; set; }
        DateTime? TimeSent { get; set; }
        public string MessageBody { get; set; }
        public PhoneNumber FromNumber { get; set; }
        public string ToNumber { get; set; }
        public DateTime? DataSent { get; internal set; }
        public MessageResource.StatusEnum MessageStatus { get; internal set; }

        public class FullSmsDetailList
        {
            public List<FullSmsDetailModel> SmsMessages { get; set; }
        }
    }
}

SendAndRecieveSMS/Models/SendMessageModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SendAndRecieveSMS.Models
{
    public class SendMessageModel
    {
        [Required(ErrorMessage = "You must provide a message")]
        public string MyMessage { get; set; }
    }
}

SendAndRecieveSMS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SendAndRecieveSMS.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SendAndRecieveSMS/Controllers/SmsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;

using Twilio;
using Twilio.Rest.Api.V2010.Account;
using Twilio.Types;

using Twilio.TwiML;
using Twilio.AspNet.Mvc;
using SendAndRecieveSMS.Models;

namespace SendAndRecieveSMS.Controllers
{
    public class SmsController : Controller
    {

        public string To => ConfigurationManager.AppSettings["MyNumber"];
        private PhoneNumber From { get; } = new PhoneNumber("+447492881517");

        public string accountSid => ConfigurationManager.AppSettings["TwilioAccountSid"];
        public string authToken => ConfigurationManager.AppSettings["TwilioAuthToken"];

        // GET: Sms
        public ActionResult SendMySms(SendMessageModel model)
        {
            
            TwilioClient.Init(accountSid, authToken);

            var myMessageToSend = (MessageResource)null;

            if (ModelState.IsValid)
            {
                //get the users message
                string getMyMessageToSend = MyHelpers.PageHelpers.HtmlRawCleanup(model.MyMessage);

                //check the length of the string first.
                int count = 0;
                foreach (char c in getMyMessageToSend)
                {
                    count++;
                }

                if(count > 160)
                {
                    TempData["ErrMsg"] = "Sorry, You're only allow to send up to 160 characters. Your current character count is: " + count;
                    return View("~/Views/Home/Index.cshtml");
                }
                else
                {
                    //send message to mobile
                    myMessageToSend = MessageResource.Create(
                    to: To,
                    from: From,
                    body: getMyMessageToSend);
                    TempData["SmsSent"] = "Your message has been sent, your reference No. is: " + myMessageToSend.Sid;
                }

               
            }
            else
            {
                TempData["ErrMsg"] = "Sorry, you need to provide a message...";
                return View("~/Views/Home/Index.cshtml");
            }
            return View("~/Views/Home/Index.cshtml");
        }
    
        
    }
}

SendAndRecieveSMS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SendAndRecieveSMS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    This is how to find us?
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:jamie.webcsltd@outlook.com">jamie.webcsltd@outlook.com</a>
</address>

SendAndRecieveSMS/Views/Home/Index.cshtml
@using SendAndRecieveSMS.MyHelpers
@using Twilio.Types
@{
    ViewBag.Title = "Home Page";
    var allMessages = PageHelpers.GetMyMessages();
}

<div class="jumbotron" style="background:url(https://www.staffcircle.com/wp-content/uploads/2018/04/home-page-banner1.jpg) no-repeat center top;">
    <h1>Staff Circle</h1>
    <p class="lead">Welcome to your customer SMS Managment Console.</p>
    <p>Multi-Channel Employee Relationship Management</p>
    <p><a href="https://www.staffcircle.com/" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2> Send an SMS</h2>
        @{
            if (TempData["SmsSent"] != null)
            {
                <div class="alert alert-error">
                    <p class="message-info">@TempData["SmsSent"]</p>
                </div>

            }
            else
            {
                if (TempData["ErrMsg"] != null)
                {
                    <div class="alert alert-error">
                        <p class="message-info">@TempData["ErrMsg"]</p>
                    </div>

                }
            }

        }
        <p>
            Send an SMS to your Friend
        </p>
        <div>
            @Html.Partial("_SendSms")
        </div>
    </div>
    <div class="col-md-4">
        <h2>My Messages</h2>
        <p>
            @{ 
                

                foreach(var sms in allMessages.SmsMessages.OrderByDescending(x=>x.DataSent))
                {
                    DateTime? dateSent = sms.DataSent;
                    string sid = sms.sid;
                    PhoneNumber from = sms.FromNumber;
                    string toNumber = sms.ToNumber;
                    string messageBody = sms.MessageBody;

                    <span class="fill"><b>Date Sent: </b>@dateSent</span><br />
                    <span class="fill"><b>SID: </b>@sid</span><br />
                    <span class="fill"><b>From: </b>@from
                     <b> | To: </b>@toNumber</span><br />
                    <span class="fill"><b>Message: </b>@messageBody</span>
                }
            }
        </p>
    </div>
    <div class="col-md-4">
        <h2>Successfully Delivered Messages </h2>
        <p>here are a list of sms's that have been deliverd</p>
        @{


            int countSms = allMessages.SmsMessages.Where(x => x.MessageStatus.ToString().ToLower() == "delivered").Count();
            int failedSMS = allMessages.SmsMessages.Where(x => x.MessageStatus.ToString().ToLower() == "failed" || x.MessageStatus.ToString().ToLower() == "undelivered").Count();


                <span class="fill"><b>SMS's Delivered: </b>@countSms</span><br />
                <span class="fill"><b>SMS's Failed or Undelivered: </b>@failedSMS</span>
        }
    </div>
</div>

SendAndRecieveSMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Send SMS Messages", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SendAndRecieveSMS/Views/Shared/_SendSms.cshtml
@model SendAndRecieveSMS.Models.SendMessageModel


<div class="forms-fields">
    @{
        using (Html.BeginForm("SendMySms", "Sms"))
        {
            <div class="field-area">
                <label class="AccessibleOnly">Message:</label> @this.Html.TextAreaFor(x => x.MyMessage, new { placeholder = "add your message" })
                <span>@Html.ValidationMessageFor(x => x.MyMessage)</span>
            </div>

            <input class="btn btn-reg" type="submit" value="Send your message" />
        }
    }
</div>